#!name=Locket Gold TEST 🏅
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
#!version= 9

[Script]
# ～ Egern transfer to Shadowrocket & Surge & LanceX
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/VthongVthongVthong/shadow/main/js/Locket_Ohoang7.js, requires-body=true, max-size=-1, timeout=60

deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/VthongVthongVthong/shadow/main/module/deleteHeader.js, timeout=60

# Runs forceGold.js on RevenueCat responses (adjust type if needed)
forceGold = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^\/]+$), script-path=https://raw.githubusercontent.com/VthongVthongVthong/shadow/main/Locket/forceGold.js, requires-body=true, max-size=-1, timeout=120

[MITM]
hostname = %APPEND% api.revenuecat.com
Beta
0 / 0
used queries
