#!name=RoPhim App Modifier
#!desc=Plugin để xử lý các yêu cầu api của ứng dụng RoPhim (RoTeam)
#!author=dabeecao & hscavn & chatgpt

[Script]
http-response ^https?:\/\/api\.rofilm\.net\/api\/app\/v1\/(?:auth\/(?:register|login)|user\/info)$ script-path=https://raw.githubusercontent.com/VthongVthongVthong/shadow/main/RoPhim/rphimx.js, requires-body=true, max-size=-1

[MITM]
hostname = api.rofilm.net
